#   _____ _                            _                     
#  / ____| |                          | |                    
# | |    | |__   __ _ _ __   __ _  ___| |     ___   __ _ ___ 
# | |    | '_ \ / _` | '_ \ / _` |/ _ \ |    / _ \ / _` / __|
# | |____| | | | (_| | | | | (_| |  __/ |___| (_) | (_| \__ \
#  \_____|_| |_|\__,_|_| |_|\__, |\___|______\___/ \__, |___/
#                            __/ |                  __/ |    
#                           |___/                  |___/     

UiTitle: "Our server Changelogs"
Text: "1 this have been added \n 2 second thing "
CloseButton: "Close"